version: "3"
services:
  app:
    environment:
      - DEBUG=FALSE
    command: bash -c "python manage.py collectstatic --noinput && gunicorn --no-sendfile --reload -b:8080 recipescape_api.wsgi"
    ports:
      - "8080:8080"
