# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-10 05:39
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clustering',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('dish_name', models.TextField()),
                ('points', django.contrib.postgres.fields.jsonb.JSONField(default=[])),
            ],
        ),
    ]
