# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-18 07:45
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clustering',
            name='centers',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=[]),
        ),
    ]
