# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-07 03:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tagger_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='last_assigned',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
