# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 07:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tagger_api', '0002_recipe_group_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotation',
            name='recipe_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tagger_api.Recipe', to_field='origin_id'),
        ),
    ]
