# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 07:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tagger_api', '0003_auto_20170727_0721'),
    ]

    operations = [
        migrations.RenameField(
            model_name='annotation',
            old_name='recipe_id',
            new_name='recipe',
        ),
    ]
