# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 07:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tagger_api', '0004_auto_20170727_0732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotation',
            name='annotated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
