# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-10 02:41
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annotator', models.CharField(max_length=100)),
                ('annotated_at', models.DateTimeField(auto_now_add=True)),
                ('annotations', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_id', models.CharField(max_length=255, unique=True)),
                ('group_name', models.CharField(default='Etc', max_length=100)),
                ('title', models.TextField()),
                ('image_url', models.URLField()),
                ('ingredients', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None)),
                ('instructions', django.contrib.postgres.fields.jsonb.JSONField()),
                ('sentences', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None)),
                ('last_assigned', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddField(
            model_name='annotation',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tagger_api.Recipe', to_field='origin_id'),
        ),
        migrations.AddField(
            model_name='annotation',
            name='worker',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
