# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-30 01:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tagger_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='is_unused',
            field=models.BooleanField(default=False),
        ),
    ]
