# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-14 04:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField()),
                ('token', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='RecipeURL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('group_name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ScrapedRecipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('image_url', models.URLField()),
                ('ingredients', models.TextField()),
                ('instruction', models.TextField()),
                ('scraped_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mturk_scraper.Assignment')),
            ],
        ),
        migrations.AddField(
            model_name='assignment',
            name='url',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mturk_scraper.RecipeURL'),
        ),
    ]
