# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-14 05:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mturk_scraper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
