# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-14 05:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mturk_scraper', '0002_auto_20171214_0511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapedrecipe',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
