# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-21 09:19
from __future__ import unicode_literals

from django.db import migrations, models
import mturk_scraper.utils


class Migration(migrations.Migration):

    dependencies = [
        ('mturk_scraper', '0004_auto_20171214_0548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='token',
            field=models.CharField(default=mturk_scraper.utils.generate_token, max_length=10),
        ),
    ]
