# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-21 09:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mturk_scraper', '0005_auto_20171221_0919'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeurl',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
